BOARD_SIZE = 3
EPOCHS = 100
NUM_OF_GAMES_PER_EPOCH = 10
NUM_OF_GAMES_PER_CHECKPOINT = 10
NUM_OF_OPPONENTS_PER_CHECKPOINT = 3
CHECKPOINT_INTERVAL = 20
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-2
PARALLEL_GAMES = False # Set to True to parallelize games in training
# MODEL = 'fhtw_hex/submission_konrad_lord_spreitzhofer/models/final/best_hex_model.keras'  # for the final submission
MODEL = 'models/final/best_hex_model.pth'  # enter the folder to test
